spring:
  datasource:
    url: jdbc:mysql://localhost:3306/courseimooc?characterEncoding=utf-8&autoReconnect=true
    username: courseimooc
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
logging:
  level:
   com.course.server.mapper: trace