spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: system
          uri: http://127.0.0.1:9001
          predicates:
          - Path=/system/**
        - id: business
          uri: lb://business
          predicates:
          - Path=/business/**
#          文件上传网关 实际项目可以单独配置网关 防止占用带宽
        - id: file
                uri: lb://file
                predicates:
                  - Path=/file/**
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
