spring:
  application:
    name: system
  datasource:
    url: jdbc:mysql://localhost:3306/courseimooc?characterEncoding=utf-8&autoReconnect=true
    username: courseimooc
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 9002
  servlet:
    context-path: /system
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
mybatis:
  mapper-locations: classpath:/mapper/*.xml
logging:
  level:
   com.course.system.mapper: trace